[package]

name = "libsystemd-sys"
version = "0.0.1"
authors = ["Cody P Schafer <dev@codyps.com>"]
license = "LGPL-2.1+"
description = "FFI bindings to libsystemd"
repository = "https://github.com/jmesmon/rust-systemd"

# 'links' is purposefully omitted
build = "build.rs"

[dependencies]
libc = "*"

[build-dependencies]
pkg-config = "*"
