language: rust
dist: trusty
sudo: required
cache: ccache
before_install:
  - sudo add-apt-repository ppa:pitti/systemd-semaphore -y
  - sudo apt-get -qq update
  - sudo apt-get install -y intltool gperf libcap-dev libmount-dev libmount1 realpath
  - ./libsystemd-sys/build-systemd.sh

env: TARGET_ARCH=x86_64 TARGET_VENDOR=-unknown TARGET_OS=linux-gnu FEATURES=bus
rust:
  - stable
  - beta
  - nightly

script:
  - ci/script.sh

after_success:
  - ci/travis-doc-upload.sh

branches:
  only:
    - staging
    - trying
    - master
