language: rust
install:
  - sudo apt-add-repository ppa:pitti/systemd
  - sudo apt-get update -qq
  - sudo apt-get install libsystemd-journal-dev
script:
  - cargo build
  - cargo test
  - rustdoc src/lib.rs
