language: rust
dist: trusty
sudo: required
cache:
  ccache: true
  cargo: true

rust:
  - stable
  - beta
  - nightly

install:
  - rustup component add rustfmt

script:
  - ci/script

branches:
  only:
    - staging
    - trying
    - master
