language: rust
dist: trusty
sudo: required
before_install:
  - sudo add-apt-repository ppa:pitti/systemd-semaphore -y
  - sudo apt-get -qq update
  - sudo apt-get install -y intltool gperf libcap-dev libmount-dev libmount1
  - ./libsystemd-sys/build-systemd.sh
env: SYSTEMD_BUILD=1

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
