language: rust
dist: trusty
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y intltool gperf
env: SYSTEMD_BUILD=1

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
