language: rust
dist: trusty
sudo: required
cache: ccache

rust:
  - stable
  - beta
  - nightly

script:
  - ci/script

after_success:
  - ci/travis-doc-upload.sh

branches:
  only:
    - staging
    - trying
    - master
