[package]

name = "systemd"
version = "0.0.1"
authors = ["Cody P Schafer <dev@codyps.com>"]
license = "LGPL-2.1+"

[dependencies]
log = "*"

[dependencies.libsystemd-sys]
path = "libsystemd-sys"
version = "*"
