[package]

name = "systemd"
version = "0.0.7"
authors = ["Cody P Schafer <dev@codyps.com>"]
license = "LGPL-2.1+"
description = "A rust interface to libsystemd provided APIs"
repository = "https://github.com/jmesmon/rust-systemd"
include = ["Cargo.toml", "src/**/*.rs" ]

[features]
bus = ["libsystemd-sys/bus"]

[dependencies]
log = "0.*"
libc = "0.*"

[dependencies.libsystemd-sys]
path = "libsystemd-sys"
version = "0.*"
