[package]
name = "systemd"
version = "0.4.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
license = "LGPL-2.1+"
description = "A rust interface to libsystemd/libelogind provided APIs"
repository = "https://github.com/jmesmon/rust-systemd"
documentation = "https://docs.rs/crate/systemd"
include = ["Cargo.toml", "src/**/*.rs", "README.md" ]
edition = "2018"

[features]
bus = ["libsystemd-sys/bus"]
elogind = ["libsystemd-sys/elogind"]

[dependencies]
log = "~0.4"
libc = "~0.2"
utf8-cstr = "~0.1"
cstr-argument = "~0.1"
foreign-types = "0.5.0"
#enumflags2 = "^0.5"
#enumflags2_derive = "^0.5"

[dependencies.libsystemd-sys]
path = "libsystemd-sys"
version = "0.5"

[dev-dependencies]
version-sync = "0.9.1"

[profile.release]
debug = true
