[package]

name = "systemd"
version = "0.0.5"
authors = ["Cody P Schafer <dev@codyps.com>"]
license = "LGPL-2.1+"
description = "A rust interface to libsystemd provided APIs"
repository = "https://github.com/jmesmon/rust-systemd"

[dependencies]
log = "0.*"
libc = "0.*"

[dependencies.libsystemd-sys]
path = "libsystemd-sys"
version = "0.*"
