on:
  push:
    branches-ignore:
      - '**.tmp'
  pull_request:

name: build

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          override: true
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v1

      - name: apt-get update
        run: sudo apt-get -o Acquire::Retries=3 update
      - name: Install libsystemd-dev
        run: sudo apt-get -o Acquire::Retries=3 install libsystemd-dev

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  features:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          override: true

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v1

      - name: apt-get update
        run: sudo apt-get -o Acquire::Retries=3 update
      - name: Install libsystemd-dev
        run: sudo apt-get -o Acquire::Retries=3 install libsystemd-dev

      - name: Check with no-default-features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --no-default-features

      - name: Check with only bus
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --no-default-features --features bus

      - name: Check with only journal
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --no-default-features --features journal

      - name: Check with only systemd_v245
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --no-default-features --features systemd_v245

      - name: Check with all features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --all-features
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.47.0

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v1

      - name: apt-get update
        run: sudo apt-get -o Acquire::Retries=3 update
      - name: Install libsystemd-dev
        run: sudo apt-get -o Acquire::Retries=3 install libsystemd-dev

      - name: Build everything
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --all-targets

      - name: Run all tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
